name: Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run Build
        run: echo "OK"
