name: Tests

on:
  pull_request:
  repository_dispatch:
    types: [ok-to-test-command]

jobs:
  # Branch-based pull request
  integration-trusted:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run tests
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: if [[ -z $TEST_SECRET ]]; then exit 1; else echo "OK"; fi


  # Repo owner has commented /ok-to-test on a (fork-based) pull request
  integration-fork:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    if: |
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.args.named.sha != '' &&
      contains(
        github.event.client_payload.pull_request.head.sha,
        github.event.client_payload.slash_command.args.named.sha
      )
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
      - name: Run tests
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: if [[ -z $TEST_SECRET ]]; then exit 1; else echo "OK"; fi
