name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: ok-to-test
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run tests
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: if [[ -z $TEST_SECRET ]]; then exit 1; else echo "OK"; fi
